spring:
  datasource:
    url: jdbc:postgresql://db:5432/sportverein
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop  # F체r Entwicklung, 채ndere zu 'update' f체r Produktion
    show-sql: true
    defer-datasource-initialization: true  # Erlaubt SQL-Initialisierung nach Hibernate
  sql:
    init:
      mode: always  # SQL-Dateien immer ausf체hren

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
